const PROJECT_STATUS_CREATED = "Created";
const PROJECT_STATUS_WAITING_FOR_INPUT = "Waiting for Input";
const PROJECT_STATUS_INPUT_PROVIDED = "Input Provided";
const PROJECT_SETUP_STATUS = new Set([
  PROJECT_STATUS_CREATED,
  PROJECT_STATUS_WAITING_FOR_INPUT,
  PROJECT_STATUS_INPUT_PROVIDED,
]);

export {
  PROJECT_STATUS_CREATED,
  PROJECT_STATUS_WAITING_FOR_INPUT,
  PROJECT_STATUS_INPUT_PROVIDED,
  PROJECT_SETUP_STATUS,
};
