const PROJECT_STATUS_CREATED = "Created";
const PROJECT_STATUS_WAITING_FOR_INPUT = "Waiting for Input";
const PROJECT_STATUS_INPUT_PROVIDED = "Input Provided";
const PROJECT_SETUP_STATUS = new Set([
	PROJECT_STATUS_CREATED,
	PROJECT_STATUS_WAITING_FOR_INPUT,
	PROJECT_STATUS_INPUT_PROVIDED,
]);

const QUESTION_FUNCTIONAL = 'Functional';
const QUESTION_TECHNICAL = 'Technical';
const QUESTION_PHASE = 'Phase';



export {
	PROJECT_STATUS_CREATED,
	PROJECT_STATUS_WAITING_FOR_INPUT,
	PROJECT_STATUS_INPUT_PROVIDED,
	PROJECT_SETUP_STATUS,
	QUESTION_FUNCTIONAL,
	QUESTION_TECHNICAL,
	QUESTION_PHASE
};
